name: Process EDA and Upload to Hopsworks

on:
  schedule:
    - cron: "15 */1 * * *"  # runs 15 minutes after fetch_data
  workflow_dispatch:

jobs:
  run-eda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}" >> .env
          echo "HOPSWORKS_API_KEY=${{ secrets.HOPSWORKS_API_KEY }}" >> .env

      - name: Run EDA script
        run: python scripts/eda.py
